/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namechanger;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class AdvancedOptions extends javax.swing.JDialog {
    NameChanger nc;
    NameChangerInterface nci;
    /**
     * Creates new form AdvancedOptions
     */
    public AdvancedOptions(NameChanger nc, NameChangerInterface nci) {
        initComponents();
        this.setAlwaysOnTop(true);
        this.nc = nc;
        this.nci= nci;
        System.out.println("start");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeSubDir = new javax.swing.JCheckBox();
        beginWithCapitalLetter = new javax.swing.JCheckBox();
        changeDirsName = new javax.swing.JCheckBox();
        changeFilesName = new javax.swing.JCheckBox();
        EraseAccentMarks = new javax.swing.JCheckBox();
        deleteLastSpaces = new javax.swing.JCheckBox();
        changeRootDirName = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        changeSubDir.setSelected(true);
        changeSubDir.setText("Change the subs dirs");

        beginWithCapitalLetter.setSelected(true);
        beginWithCapitalLetter.setText("Begin with capital letters");

        changeDirsName.setSelected(true);
        changeDirsName.setText("Change dirs name");

        changeFilesName.setSelected(true);
        changeFilesName.setText("Change files name");

        EraseAccentMarks.setSelected(true);
        EraseAccentMarks.setText("Erase accent marks");

        deleteLastSpaces.setSelected(true);
        deleteLastSpaces.setText("Delete the last spaces");

        changeRootDirName.setSelected(true);
        changeRootDirName.setText("Change the root dir name");

        jButton1.setText("Aceptar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeSubDir)
                    .addComponent(changeDirsName)
                    .addComponent(beginWithCapitalLetter)
                    .addComponent(changeRootDirName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changeFilesName)
                    .addComponent(EraseAccentMarks)
                    .addComponent(deleteLastSpaces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeSubDir)
                    .addComponent(changeFilesName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beginWithCapitalLetter)
                    .addComponent(EraseAccentMarks))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeDirsName)
                    .addComponent(deleteLastSpaces))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeRootDirName)
                    .addComponent(jButton1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        this.nc.setEraseAccentMarks(this.EraseAccentMarks.isSelected());
        this.nc.setBeginWithMayus(this.beginWithCapitalLetter.isSelected());
        this.nc.setChangeDirsName(this.changeDirsName.isSelected());
        this.nc.setChangeFileName(this.changeFilesName.isSelected());
        this.nc.setChangeRootDir(this.changeRootDirName.isSelected());
        this.nc.setChangeSubDir(this.changeSubDir.isSelected());
        this.nc.setDeleteLastSpace(this.deleteLastSpaces.isSelected());
        this.setVisible(false);
        nci.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox EraseAccentMarks;
    private javax.swing.JCheckBox beginWithCapitalLetter;
    private javax.swing.JCheckBox changeDirsName;
    private javax.swing.JCheckBox changeFilesName;
    private javax.swing.JCheckBox changeRootDirName;
    private javax.swing.JCheckBox changeSubDir;
    private javax.swing.JCheckBox deleteLastSpaces;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
