/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namechanger;

/**
 *
 * @author Usuario
 */
public class Help extends javax.swing.JDialog {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
    }
    
    public void setHelp(int type){
        String message="";
        switch (type) {
            case 1: //Change sub dirs
                message+="This changes the dirs/files \ninside the dirs "
                        + "that are inside \nof the root dir you have chosen.";
                break;
            case 2: //Change files name
                message+="This changes the name of the \nfiles.";
                break;
            case 3:  //Begin with capital letters
                message+="This changes the first letter \nof the dir/file "
                        + "name to \ncapital letter.";
                break;
            case 4: //Erase accent marks
                message+="This changes the letters with \naccent marks to the "
                        + "same letter \nwithout the accent mark.";
                break;
            case 5: //Change dirs name
                message+="This changes the dirs name.";
                break;
            case 6: //Delete the last space
                message+="This changes the dir/file \nname from \"File .txt\" \nto "
                        + "\"File.txt\".";
                break;
            case 7: //Change the root dir name
                message+="This changes the root dir name.";
                break;
        }
        this.message.setText(message);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        message.setEditable(false);
        message.setColumns(20);
        message.setRows(5);
        message.setAutoscrolls(false);
        message.setDoubleBuffered(true);
        message.setDragEnabled(true);
        message.setFocusable(false);
        message.setOpaque(false);
        message.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(message);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea message;
    // End of variables declaration//GEN-END:variables
}
