/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namechanger;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author Usuario
 */
public class NameChangerInterface extends javax.swing.JDialog {
    NameChanger nc;
    AdvancedOptions advancedOptionsPage = null;
    Message myMessage = null;
    /**
     * Creates new form nameChangerInterface
     */
    public NameChangerInterface(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        nc = new NameChanger();
        initComponents();
        this.jButton2.setVisible(false);
        this.nc.setEraseAccentMarks(true);
        this.nc.setBeginWithMayus(true);
        this.nc.setChangeDirsName(true);
        this.nc.setChangeFileName(true);
        this.nc.setChangeRootDir(true);
        this.nc.setChangeSubDir(true);
        this.nc.setDeleteLastSpace(true);
        this.getContentPane().setBackground( Color.white );
        this.theFile.setVisible(false);
        this.setSize(400, 227);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        theFile = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        spaces = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        theFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        theFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("advancedOptions");
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        spaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not to change spaces", "Change spaces by low bar", "Change spaces by script", "Delete space", "Delete space (Next letter on capital)" }));
        spaces.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spaces.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        spaces.setPreferredSize(new java.awt.Dimension(199, 25));
        spaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spacesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NameChanger");

        select.setText("Select file or dir");
        select.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setText("Start!");
        jButton2.setActionCommand("Start");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(theFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(spaces, 0, 220, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaces, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(theFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(select)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(this.myMessage==null){
            this.myMessage = new Message(nc, this);
            this.myMessage.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            this.myMessage.setLocationRelativeTo(null);
            this.myMessage.setResizable(false);
        }
        this.myMessage.setVisible(true);
        this.myMessage.setAlwaysOnTop(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseClicked
        // TODO add your handling code here:
        JFileChooser selecter = new JFileChooser();
        selecter.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        selecter.showOpenDialog(this);
        File file = selecter.getSelectedFile(); // obtiene el archivo seleccionado
        if ((file == null) || (file.getName().equals("")) || !file.exists()) {
            this.theFile.setForeground(Color.red);
            this.theFile.setText("No se ha seleccionado ningun archivo o directorio valido");
            this.jButton2.setVisible(false);
            this.setSize(400, 260);
        }
        else{
            nc.setRootDir(file);
            int index = spaces.getSelectedIndex();
            boolean changeWithLowBar = false;
            boolean changeWithScript = false;
            boolean changeWithMayus = false;
            boolean changeWithoutMayus = false;
            if(index == 1) changeWithLowBar = true;
            else if(index == 2) changeWithScript = true;
            else if(index == 3) changeWithMayus = true;
            else if(index == 4) changeWithoutMayus = true;
            nc.setChangeWithLowBar(changeWithLowBar);
            nc.setChangeWithScript(changeWithScript);
            nc.setChangeWithMayus(changeWithMayus);
            nc.setChangeWithoutMayus(changeWithoutMayus);
            String whatIs ="";
            if(file.isDirectory()) whatIs ="Dir: ";
            else if(file.isFile()) whatIs ="File: ";
            this.theFile.setForeground(Color.BLACK);
            this.theFile.setText(whatIs+file.getAbsolutePath());
            this.jButton2.setVisible(true);
            this.setSize(400, 300);
        }
        this.theFile.setVisible(true);
    }//GEN-LAST:event_selectMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(advancedOptionsPage==null){
            advancedOptionsPage = new AdvancedOptions(nc, this);
            advancedOptionsPage.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            advancedOptionsPage.setLocationRelativeTo(null);
            advancedOptionsPage.setResizable(false);
        }
        advancedOptionsPage.setVisible(true);
        advancedOptionsPage.setAlwaysOnTop(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void spacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spacesActionPerformed

    public void restart(){
        nc = null;
        advancedOptionsPage = null;
        myMessage.setVisible(false);
        myMessage = null;
        spaces.setSelectedIndex(0);
        theFile.setText("");
        this.setVisible(false);
        this.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NameChangerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NameChangerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NameChangerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NameChangerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NameChangerInterface dialog = new NameChangerInterface(new javax.swing.JFrame(), true);
                dialog.setLocationRelativeTo(null); 
                dialog.setResizable(false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton select;
    private javax.swing.JComboBox<String> spaces;
    private javax.swing.JLabel theFile;
    // End of variables declaration//GEN-END:variables
}
