/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package namechanger;

/**
 *
 * @author Javi
 */
public class options extends javax.swing.JDialog {

    /**
     * Creates new form options
     */
    public options(String rootDir) {
        this.rootDir = rootDir;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subDir = new javax.swing.JCheckBox();
        theSpaces = new javax.swing.JComboBox<>();
        beginOnCapital = new javax.swing.JCheckBox();
        accentMarks = new javax.swing.JCheckBox();
        deleteLastSpace = new javax.swing.JCheckBox();
        changeFileName = new javax.swing.JCheckBox();
        changeDirName = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        subDir.setSelected(true);
        subDir.setText("Change sub dir");
        subDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subDirActionPerformed(evt);
            }
        });

        theSpaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Change spaces with low bar", "Change spaces with script", "Delete spaces", "Delete spaces next letter in capital" }));
        theSpaces.setToolTipText("");

        beginOnCapital.setSelected(true);
        beginOnCapital.setText("First letter on capital");

        accentMarks.setSelected(true);
        accentMarks.setText("Erase accent marks");

        deleteLastSpace.setSelected(true);
        deleteLastSpace.setText("Delete the last space");

        changeFileName.setSelected(true);
        changeFileName.setText("Change files name");

        changeDirName.setSelected(true);
        changeDirName.setText("Change dirs name");

        jToggleButton1.setText("Lets change");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Delete the last space");
        jCheckBox1.setActionCommand("lastSpace");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteLastSpace)
                                .addGap(63, 63, 63)
                                .addComponent(changeDirName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(beginOnCapital)
                                .addGap(65, 65, 65)
                                .addComponent(jCheckBox1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subDir)
                                .addGap(70, 70, 70)
                                .addComponent(theSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accentMarks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeFileName)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subDir)
                    .addComponent(theSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beginOnCapital)
                    .addComponent(jCheckBox1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accentMarks)
                    .addComponent(changeFileName))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLastSpace)
                    .addComponent(changeDirName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subDirActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        boolean changeWithLowBar = false;
        boolean changeWithScript = false;
        boolean changeWithMayus = false;
        boolean changeWithoutMayus = false;
        if(theSpaces.getSelectedIndex() == 1) changeWithLowBar = true;
        else if(theSpaces.getSelectedIndex() == 2) changeWithScript = true;
        else if (theSpaces.getSelectedIndex() == 3) changeWithoutMayus = true;
        else if(theSpaces.getSelectedIndex() == 4) changeWithMayus = true;
        NameChanger nc = new NameChanger(this.subDir.isSelected(), this.beginOnCapital.isSelected(), changeWithLowBar, 
                                        changeWithScript, changeWithMayus, changeWithoutMayus, this.changeDirName.isSelected(), 
                                        this.changeFileName.isSelected(), this.accentMarks.isSelected(), this.deleteLastSpace.isSelected(), 
                                        this.rootDir);
        nc.changeTheNames();
        System.exit(0);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private String rootDir;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox accentMarks;
    private javax.swing.JCheckBox beginOnCapital;
    private javax.swing.JCheckBox changeDirName;
    private javax.swing.JCheckBox changeFileName;
    private javax.swing.JCheckBox deleteLastSpace;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JCheckBox subDir;
    private javax.swing.JComboBox<String> theSpaces;
    // End of variables declaration//GEN-END:variables
}
